In [70]:
import numpy as np

##verilere erişme

In [71]:
dizi = np.arange(10,20)
dizi

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [72]:
dizi[5:10]

array([15, 16, 17, 18, 19])

In [73]:
#dizi[::-1] #dizi elemanlarını tersten sıralar.
dizi2 = np.random.randint(10,50,10)
dizi2.sort() #diziyi artar sıralar
#dizi2
dizi2[::-1] #diziyi tersten sıralar

array([45, 40, 35, 29, 27, 25, 17, 14, 12, 11])

##iki dizi birleştirme işlemleri

In [74]:
dizi1 = np.random.randint(-20,20,(4,4))
dizi2 = np.random.randint(30,50,(4,4))
dizi2.sort()
dizi2


array([[37, 43, 43, 47],
       [39, 40, 42, 47],
       [31, 37, 41, 46],
       [34, 38, 41, 45]])

In [75]:
np.concatenate([dizi1,dizi2]) #dizi değerlerini birleştirmek için kullanılır.
dizi2.sort()
dizi2

array([[37, 43, 43, 47],
       [39, 40, 42, 47],
       [31, 37, 41, 46],
       [34, 38, 41, 45]])

In [84]:
bosListe = []
sayiListe = []
for i in range(4):
    eleman = input("kişi gir: ")
    bosListe.append(eleman)

for i in range(4):
    eleman = int(input("sayi gir: "))
    sayiListe.append(eleman)
    

deger = np.array(bosListe)
sayi = np.array(sayiListe)
sayi2 = sayi.reshape((2,2))
deger2 = deger.reshape((2,2))
print(deger2)
print(sayi2)
np.concatenate((deger2,sayi2))
    
    
    
    
    
    
    
    

[['2' '2']
 ['3' '3']]
[[4 4]
 [5 5]]


array([['2', '2'],
       ['3', '3'],
       ['4', '4'],
       ['5', '5']], dtype='<U11')