In [51]:
import numpy as np
myList = ["emre"]
myList = np.array([[5,6,7],[0,1,2],[10,11,12]]) #
myList 

array([[ 5,  6,  7],
       [ 0,  1,  2],
       [10, 11, 12]])

In [52]:
myList2 = []
myList2 = np.array([["emre","eren"],["arda","c"],["a","b"]])
myList2

array([['emre', 'eren'],
       ['arda', 'c'],
       ['a', 'b']], dtype='<U4')

In [53]:
myList = list(range(0,20,2))
myList

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [54]:
mylist2 = np.arange(0,20,2)
mylist2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [55]:
sifirDizisi = np.zeros((4,8))
sifirDizisi

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [56]:
birlerDizisi = np.ones((3,3))
birlerDizisi

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [57]:
aralikDizi = np.linspace(0,10,20)
aralikDizi

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [58]:
rastgeleDizi = np.random.randn(10)
rastgeleDizi

array([-0.59395325,  0.78549521,  0.63883171,  1.49215545,  0.77494804,
        0.71532456, -1.33853706, -0.26756045, -1.12338957, -1.79854522])

In [59]:
rastgeleDizi = np.random.randn(7,2,4)
rastgeleDizi

array([[[ 0.82821953,  0.1359136 , -0.51171375,  0.87642929],
        [ 0.076555  , -0.8790959 ,  1.17191862,  0.09814158]],

       [[ 0.74967019, -0.99319911,  0.12404828, -0.16716203],
        [-1.81469681,  0.34457973, -0.99429841,  0.35041215]],

       [[-1.34845559,  0.39574073, -0.45843404, -0.62628552],
        [ 0.4918568 ,  1.90818604,  0.68243635,  0.56005862]],

       [[-0.70561779, -0.17373523,  0.23660221, -0.13444236],
        [-1.80689372,  1.43658252, -0.48215579, -0.0971018 ]],

       [[-0.20981466,  0.33767465, -0.68042515, -0.95149363],
        [-1.02887735,  1.9853474 ,  0.12892239,  2.22632026]],

       [[ 1.07914485, -0.02823938, -0.75231829, -1.46414587],
        [ 0.71156878,  0.49823954, -0.69094514,  0.58231855]],

       [[ 0.73979458, -0.60519649, -0.73886292,  0.53601421],
        [ 0.15558598,  1.01748012,  0.40484501, -0.76150557]]])

In [60]:
#np.random.randint(baslangıc,bitis,artış) veya
#np.random.randint(baslangıc,bitis,matrisDegeri)

rastgeleTamSayi = np.random.randint(10,20,(1,2))
rastgeleTamSayi

array([[18, 12]])