In [1]:
import numpy as np


In [2]:
myList = list(range(0,20,2))
myList

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [3]:
mylist2 = np.arange(0,20,2)
mylist2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
sifirDizisi = np.zeros((4,8))
sifirDizisi

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [11]:
birlerDizisi = np.ones((3,3))
birlerDizisi

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# aralık belirtme işlemi linspace

In [15]:
aralikDizi = np.linspace(0,10,20)
aralikDizi

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

# Rastgele ondalıklı Sayı Dizisi

In [17]:
rastgeleDizi = np.random.randn(10)
rastgeleDizi

array([ 0.67973322,  2.60199687,  1.12792097,  1.14658979,  0.02389618,
        1.53021618,  1.12629142,  0.36642122,  0.11533083, -0.73980067])

In [21]:
rastgeleDizi = np.random.randn(7,2,4)
rastgeleDizi

array([[[-0.68086857, -0.2340267 ,  1.75217652,  0.28542258],
        [-1.74635866,  0.5118604 , -1.60079964, -0.40335564]],

       [[-0.49626928, -0.29589076, -0.31905263, -1.51968862],
        [-0.09678812,  0.27839954, -0.5805992 ,  0.25990338]],

       [[-1.62107284,  0.24257451,  1.0637659 ,  0.70074437],
        [ 1.9569    , -0.969991  ,  2.01038482,  1.35471949]],

       [[ 0.80359805,  0.19160938,  0.73992997, -0.50391961],
        [-0.7797235 ,  0.57947697,  1.15533617, -0.71747278]],

       [[ 0.30041406,  0.45747143, -0.45575225,  0.87645455],
        [-0.52832115, -0.44521327, -1.86787224,  2.12939307]],

       [[-0.96913462,  0.21599742, -0.06804455, -0.02595219],
        [-0.12825015, -0.34848959, -1.6436583 , -0.15724667]],

       [[-0.64720777, -0.94391564,  1.1505336 , -0.4673824 ],
        [-1.57283714, -1.42641321,  1.36932515,  0.14419086]]])

# Rastgele ondalıklı Sayı Dizisi

In [33]:
#np.random.randint(baslangıc,bitis,artış) veya
#np.random.randint(baslangıc,bitis,matrisDegeri)

rastgeleTamSayi = np.random.randint(10,20,(1,2))
rastgeleTamSayi

array([[17, 10]])

# belirttiğiniz Değer ile Diziyi oluşturma

In [39]:
dizi = np.full(((4,4)), round(53.83472,2), dtype = "float")
dizi

array([[53.83, 53.83, 53.83, 53.83],
       [53.83, 53.83, 53.83, 53.83],
       [53.83, 53.83, 53.83, 53.83],
       [53.83, 53.83, 53.83, 53.83]])

# Reshape Kullanımı

In [47]:
dizi = np.random.randint(10,20,(2,2))
dizi.reshape(2,2)


array([[14, 18],
       [11, 18]])

In [49]:
print("en büyük: ", dizi.max())
print("en küçük: ", dizi.min())
print("büyük indis no: ", dizi.argmax())
print("küçük indis no: ", dizi.argmin())


en büyük:  18
en küçük:  11
büyük indis no:  1
küçük indis no:  2
